version: '3.8'

services:
  avito-app:
    build: ./
    command: ./wait_for_postgres.sh avito-db ./avito-app
    ports:
      - 8000:8000
    depends_on:
      - avito-db
    environment:
      - DB_PASSWORD=qwerty

  avito-db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432